# Generated by Django 3.2.4 on 2021-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='aaaaaaaaaaaaa', max_length=200),
            preserve_default=False,
        ),
    ]
